"""add aggregator tables

Revision ID: 6d56d98e0c59
Revises: 8c5b79466278
Create Date: 2026-04-18 19:52:24.238225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d56d98e0c59'
down_revision = '8c5b79466278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_show',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('premiered', sa.String(length=10), nullable=True),
    sa.Column('oldest_year', sa.String(length=4), nullable=True),
    sa.Column('studio', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aggregated_channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.String(length=50), nullable=True),
    sa.Column('channel_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['aggregated_show.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aggregated_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('show_id', sa.String(length=50), nullable=True),
    sa.Column('video_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('published_at', sa.String(length=10), nullable=True),
    sa.Column('season', sa.String(length=4), nullable=True),
    sa.Column('episode', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['aggregated_show.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aggregated_video')
    op.drop_table('aggregated_channel')
    op.drop_table('aggregated_show')
    # ### end Alembic commands ###
