"""add is_enabled to aggregator tables

Revision ID: 6ec312e45c5b
Revises: 6d56d98e0c59
Create Date: 2026-04-30 01:11:07.648311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec312e45c5b'
down_revision = '6d56d98e0c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('aggregated_video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_video', schema=None) as batch_op:
        batch_op.drop_column('is_enabled')

    with op.batch_alter_table('aggregated_channel', schema=None) as batch_op:
        batch_op.drop_column('is_enabled')

    # ### end Alembic commands ###
