"""add custom assets flag to channels and aggregated shows

Revision ID: 7a480487d0d5
Revises: 6ec312e45c5b
Create Date: 2026-05-07 06:09:06.503266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a480487d0d5'
down_revision = '6ec312e45c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregated_show', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_custom_assets', sa.Boolean(), nullable=True))

    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_custom_assets', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_column('has_custom_assets')

    with op.batch_alter_table('aggregated_show', schema=None) as batch_op:
        batch_op.drop_column('has_custom_assets')

    # ### end Alembic commands ###
